name: Deploy

on:
  #push:
    #branches:
      #- main
  workflow_dispatch:

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Node.js manually
        run: |
          curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Check Node.js version
        run: node -v

      - name: List directory contents for debugging
        run: ls -al
      
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Comprobar que se accede al secreto
        run: echo "My existing secret is ${{ secrets.OPENAI_API_KEY }}"
        
      - name: Deploy
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          # Add commands to deploy your project, e.g., upload to a server, etc.
          
      - name: Start server
        run: node server.js
